services:
  - type: web
    name: andrew-stack-template-web
    runtime: docker
    branch: main
    healthCheckPath: /health
    envVars:
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: andrew-stack-template-db
          property: connectionString

databases:
  - name: andrew-stack-template-db
    databaseName: prod
